//
//  STPhotoMapModels.swift
//  STPhotoMap
//
//  Created by Crasneanu Cristian on 12/04/2019.
//  Copyright (c) 2019 mikelanza. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
import MapKit

enum STPhotoMapModels {
    enum VisibleTiles {
        struct Request {
            let tiles: [TileCoordinate]
        }
    }
    
    enum EntityZoomLevel {
        struct Response {
            let entityLevel: EntityLevel
        }
        
        struct ViewModel {
            let title: String?
            let image: UIImage?
        }
    }
    
    struct Annotation {
        let id: String
        let imageUrl: String?
        let latitude: Double
        let longitude: Double
        
        func toPhotoAnnotation() -> PhotoAnnotation {
            let pinAnnotation = PhotoAnnotation(id: id, coordinate: CLLocationCoordinate2D(latitude: self.latitude, longitude: self.longitude))
            pinAnnotation.model.imageUrl = imageUrl
            return pinAnnotation
        }
    }
    
    enum LocationAnnotations {
        struct Response {
            let annotations: [Annotation]
        }
        
        struct ViewModel {
            let annotations: [PhotoAnnotation]
        }
    }
    
    enum PhotoAnnotationImageDownload {
        struct Request {
            let photoAnnotation: PhotoAnnotation
        }
    }
    
    enum PhotoAnnotationSelection {
        struct Request {
            let photoAnnotation: PhotoAnnotation
            let previousPhotoAnnotation: PhotoAnnotation?
        }
    }
    
    enum PhotoDetailsNavigation {
        struct Response {
            let photoId: String?
        }
        
        struct ViewModel {
            let photoId: String?
        }
    }
    
    enum LocationOverlay {
        struct Response {
            let photo: STPhoto
        }
        
        struct ViewModel {
            let photoId: String
            let title: String?
            let time: String?
            let description: String?
        }
    }
}
