//
//  STPhotoMapRouter.swift
//  STPhotoMap
//
//  Created by Crasneanu Cristian on 12/04/2019.
//  Copyright (c) 2019 Streetography. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
import SafariServices
import STPhotoDetails
import STPhotoCore
import STPhotoCollection

protocol STPhotoMapRoutingLogic: AnyObject {
    func navigateToSafari(url: URL)
    func navigateToLocationSettingsAlert(controller: UIAlertController)
    func navigateToApplication(url: URL)
    func navigateToPhotoDetails(viewController: UIViewController?, photoId: String)
    func navigateToPhotoCollection(location: STLocation, entityLevel: EntityLevel, userId: String?, collectionId: String?)
    
    var viewController: UIViewController? { get set }
    var photoMapView: STPhotoMapView? { get set }
}

class STPhotoMapRouter: NSObject, STPhotoMapRoutingLogic {
    weak var displayer: STPhotoMapDisplayLogic?
    weak var viewController: UIViewController?
    weak var photoMapView: STPhotoMapView?
    
    // MARK: Routing
    
    func navigateToSafari(url: URL) {
        let safariViewController = SFSafariViewController(url: url)
        self.viewController?.present(safariViewController, animated: true, completion: nil)
    }
        
    func navigateToLocationSettingsAlert(controller: UIAlertController) {
        self.viewController?.present(controller, animated: true, completion: nil)
    }
    
    func navigateToApplication(url: URL) {
        if UIApplication.shared.canOpenURL(url) {
            UIApplication.shared.open(url)
        }
    }
    
    func navigateToPhotoDetails(viewController: UIViewController?, photoId: String) {
        let photoDetailsViewController = STPhotoDetailsViewController(photoId: photoId)
        if let navigationController = viewController?.navigationController {
            navigationController.pushViewController(photoDetailsViewController, animated: true)
        } else {
            viewController?.present(photoDetailsViewController, animated: true, completion: nil)
        }
    }
    
    func navigateToPhotoCollection(location: STLocation, entityLevel: EntityLevel, userId: String?, collectionId: String?) {
        let entity = STPhotoCollection.EntityModel(location: location, level: entityLevel)
        let filters = STPhotoCollection.FilterModel(userId: userId, collectionId: collectionId)
        let photoCollectionViewController = STPhotoCollectionViewController(model: STPhotoCollection.Model(entityModel: entity, filterModel: filters))
        photoCollectionViewController.delegate = self.photoMapView
        if let navigationController = viewController?.navigationController {
            navigationController.pushViewController(photoCollectionViewController, animated: true)
        } else {
            self.viewController?.present(UINavigationController(rootViewController: photoCollectionViewController), animated: true, completion: nil)
        }
    }
}
