//
//  STPhotoMapRouter.swift
//  STPhotoMap
//
//  Created by Crasneanu Cristian on 12/04/2019.
//  Copyright (c) 2019 mikelanza. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
import SafariServices

@objc protocol STPhotoMapRoutingLogic {
    func navigateToSafari(url: URL)
    func navigateToLocationSettingsAlert(controller: UIAlertController)
    func navigateToApplication(url: URL)
}

protocol STPhotoMapDataPassing {
    var dataStore: STPhotoMapDataStore? { get }
}

class STPhotoMapRouter: NSObject, STPhotoMapRoutingLogic, STPhotoMapDataPassing {
    weak var displayer: STPhotoMapDisplayLogic?
    var dataStore: STPhotoMapDataStore?
    
    // MARK: Routing
    
    func navigateToSafari(url: URL) {
        DispatchQueue.main.async {
            let viewController = SFSafariViewController(url: url)
            viewController.show()
        }
    }
        
    func navigateToLocationSettingsAlert(controller: UIAlertController) {
        DispatchQueue.main.async {
            controller.show()
        }
    }
    
    func navigateToApplication(url: URL) {
        DispatchQueue.main.async {
            if UIApplication.shared.canOpenURL(url) {
                UIApplication.shared.open(url)
            }
        }
    }
}
