//
//  STPhotoMapPresenter.swift
//  STPhotoMap
//
//  Created by Crasneanu Cristian on 12/04/2019.
//  Copyright (c) 2019 mikelanza. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol STPhotoMapPresentationLogic {
    
}

class STPhotoMapPresenter: STPhotoMapPresentationLogic {
    weak var viewController: STPhotoMapDisplayLogic?
}
